### ISSUE TITLE
Digital Envelopes Routine Library is unsupported

### ISSUE THREAD

**Issue by gaurav1021** [adrianhajdin/project_chat_application#115]
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:412:16)
    at handleParseError (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:463:10)
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:495:5
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:354:12
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10) 
    at iterateNormalLoaders (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10) 
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
C:\Users\gaura\projects\project_chat_application-master\client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:412:16)
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:444:10
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\webpack\lib\NormalModule.js:320:13
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\gaura\projects\project_chat_application-master\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\gaura\projects\project_chat_application-master\client\node_modules\babel-loader\lib\index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

**Comment by kabudaLiu** [comment]
node 版本切换到 14.0.0
同时删除package-lock。json与node_modules

**Comment by MashhadLeghari** [comment]
setup environment variable in client/package.json or in terminal as: set NODE_OPTIONS=--openssl-legacy-provider
![Screenshot_20230923_110401](https://github.com/adrianhajdin/project_chat_application/assets/135958555/7a7cfefa-6bc0-41f5-9b13-4c51e9ca66e3)

**Comment by venkateshatgit** [comment]
I faced same error. I did 2 changes which made my code run.

change 1: 
<img width="407" alt="image" src="https://github.com/adrianhajdin/project_chat_application/assets/72207261/b7146100-1a7c-4e32-b9ca-cd152b13e02c">

change 2: installing react version 5 -> deleting node_module -> npm cache clean -> npm install

This made the application run.
Hope this helped.
