### ISSUE TITLE
TypeError: Cannot read property 'room' of undefined

### ISSUE THREAD

**Issue by vickypotter** [adrianhajdin/project_chat_application#12]
io.to(user.room).emit('message', {user:user.name, text:message});
                   ^

TypeError: Cannot read property 'room' of undefined
    at Socket.<anonymous> (D:\React.js\Chat App\server\index.js:28:20)
    at Socket.emit (events.js:210:5)
    at D:\React.js\Chat App\server\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by vickypotter** [comment]
anyone pls give solution

**Comment by fonmagnus** [comment]
Encounter the same too

**Comment by CluelessWizard** [comment]
I had the same issue, but found what was wrong.

In my case the _getUser()_ didn't returned a user, because I used curly braces, which doesn't return anything thus it was undefined. After I checked that function in _server/users.js_ and deleted braces, my chat finally worked.

**Comment by tamysiby** [comment]
I had the same issue. I couldn't use **sendMessage** function because it returned that error. I tinkered around, and in my case, changing the _**const**_ to _**let**_ int the function when defining **user** solved the problem.

It would be great if someone would explain why it works this way, but it hey it works.

So in **_server/index.js_** 

```
socket.on('sendMessage', (message, callback) => {
        let user = getUser(socket.id);
        ...
    });
```

**Comment by brodave318** [comment]
Could be a typo. I had getUserInRoom as opposed to getUsersInRoom, using user instead of users. That's the problem I had. Also, restart the server manually whenever you make a change even if you're using nodemon. Lost a lot of time unnecessarily.

**Comment by nitinankad** [comment]
Getting this error as well. It happens when trying to restart the server. I think having some way to remember the rooms and then re-registering them to socket.io on restart might fix it. Thoughts?

**Comment by Dev-Sec0901** [comment]
I'm also facing the same issue, what I think in my case is, when a user joins a chat room with a username that is already in use, no error is being generated, so user gets entry into the user interface, but also he isn't able to send any message, so the sendMessage function crashes at the time, crashing the server.

**Comment by codeshaan** [comment]
> Getting this error as well. It happens when trying to restart the server. I think having some way to remember the rooms and then re-registering them to socket.io on restart might fix it. Thoughts?

Yeah, I agree with you. Whenever I try to refresh after joining room & sending few messages, the server crashes.It happens may be because after refreshing the 'disconnect' event if fired off!! If somehow we could remember the rooms, may be the problem will be fixed!!

**Comment by alisalim17** [comment]
I sent name in Chat and that fixed

**Comment by viswa9688** [comment]
@alisalim17 can you please share the code regarding the fix?

**Comment by harshgarg1808** [comment]
[ FIXED ] : 

In server/users.js : 

`const getUser = (id) => users.find((user)=> user.id === id) `

Remove the '{ }' after the '=>' , Code will work perfectly.

**Comment by AlvaJufinto** [comment]
I have the same issue and none of those solutions work for me.

io.to(user.room).emit('message', { user: user.name, text: message});
                   ^
TypeError: Cannot read property 'room' of undefined

**Comment by MbuguaGeorge** [comment]
> [ FIXED ] :
> 
> In server/users.js :
> 
> `const getUser = (id) => users.find((user)=> user.id === id) `
> 
> Remove the '{ }' after the '=>' , Code will work perfectly.

This works.

**Comment by Jatan88** [comment]
I am also getting the same issue.
I checked everything and there is no typo in my code but still the issue continues.

Error message: 
TypeError: Cannot read properties of undefined (reading 'room')
    at Socket.<anonymous> (C:\Users\Jatan\chat-app\server\index.js:43:20)
    at Socket.emit (node:events:520:28)
    at Socket.emitUntyped (C:\Users\Jatan\chat-app\server\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Jatan\chat-app\server\node_modules\socket.io\dist\socket.js:465:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Jatan88** [comment]
@vickypotter Have you got any solution?
